name: Test Powershell Script Action
description: Test Powershell Script Action

inputs:
  name:
    description: 'The name to include in the greeting.'
    required: true
  dotnet-version:
    description: '.NET version'
    required: false
    default: 8.0.x    
runs:
  using: composite
  steps:
    - name: Set Log Level
      shell: pwsh
      run: $InformationPreference="Continue"
    - uses: Amadevus/pwsh-script@v2
      with:
        script: $ {{ github.action_path }}/test-script.ps1         
    - name: Set Output
      id: outputstep
      shell: pwsh
      run: echo "::set-output name=greeting::${{ steps.hello.outputs.stdout }}"
